### ISSUE TITLE
v0.25 Exec format error on Catalina

### ISSUE THREAD

**Issue by eneagoe** [wtfutil/homebrew-wtfutil#1]
The latest version of the package throws an error on Catalina:

`/usr/local/bin/wtfutil: cannot execute binary file: Exec format error`

Could there be some mismatched binaries?

**Comment by eneagoe** [comment]
Is seems this is already [reported](https://github.com/wtfutil/wtf/issues/765) in upstream, so I'll close this one and wait for it to be fixed there.

**Comment by senorprogrammer** [comment]
Thanks for reporting and following up @eneagoe. This will remain an issue until Apple fixes their side of things.
